name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true # If your project uses submodules, uncomment this.

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26' # Use the desired Go version

    - name: Install Gio Linux dependencies
      run: sudo apt-get update && sudo apt-get install -y libwayland-dev libxkbcommon-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libx11-dev libx11-xcb-dev libxcursor-dev libvulkan-dev

    - name: Check formatting (go fmt)
      run: go fmt ./...

    - name: Run unit tests (go test)
      run: go test -v ./...